// Summarises the harness report of every family and candidate for checkpoint 3:
// the status of each profile, the counts, and the checks that sit closest to
// their limits. Writes docs/migration/phase3/summary.md and summary.json.
//
//   node scripts/design/phase3-summary.ts
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildReport, loadContext } from "../../lib/harness/index.ts";
import type { Check } from "../../lib/harness/index.ts";
import { loadCandidates, loadFamilies, repoRoot } from "../../lib/model/load.ts";
import { resolveFamily } from "../../lib/model/resolve.ts";

const root = repoRoot();
const thresholds = JSON.parse(readFileSync(join(root, "tests/environments.json"), "utf8"));
const ctx = loadContext();

const BOOK_ORDER = ["pequod", "goney", "townho", "jeroboam", "jungfrau", "rosebud", "enderby", "bachelor", "rachel", "delight"];
const rank = (id: string) => (BOOK_ORDER.includes(id) ? BOOK_ORDER.indexOf(id) : BOOK_ORDER.length);

interface Entry {
  name: string;
  family: string;
  candidate?: string;
  version: string;
  profiles: Record<string, { status: string; errors: number; warnings: number; waived: number; checks: number; tightest: { id: string; mode?: string; value: number; limit: number; detail: string }[] }>;
}

/** Checks that pass, carry a number and a limit, and sit closest to the limit in relative terms. */
function tightest(checks: Check[], n = 3) {
  return checks
    .filter((c) => c.ok && !c.report && !c.waived && c.value !== undefined && c.limit !== undefined && Number.isFinite(c.value))
    .map((c) => ({ c, margin: Math.abs(c.value! - c.limit!) / Math.max(Math.abs(c.limit!), 1e-9) }))
    .sort((a, b) => a.margin - b.margin)
    .slice(0, n)
    .map(({ c }) => ({ id: c.id, ...(c.mode ? { mode: c.mode } : {}), value: c.value!, limit: c.limit!, detail: c.detail }));
}

const entries: Entry[] = [];
const list = [
  ...loadFamilies().map((f) => ({ dir: f.dir, candidate: undefined as string | undefined, file: f.file })),
  ...loadCandidates().map((c) => ({ dir: c.dir, candidate: c.candidate, file: c.file })),
].sort((a, b) => rank(a.dir) - rank(b.dir) || (a.candidate ?? "").localeCompare(b.candidate ?? ""));

for (const f of list) {
  const family = resolveFamily(f.file);
  const report = buildReport(family, thresholds, ctx);
  const profiles: Entry["profiles"] = {};
  for (const [name, p] of Object.entries(report.profiles)) {
    profiles[name] = { status: p.status, errors: p.errors, warnings: p.warnings, waived: p.waived, checks: p.checks.length, tightest: tightest(p.checks) };
  }
  entries.push({ name: f.candidate ? `${f.dir} (candidate ${f.candidate})` : f.dir, family: f.dir, ...(f.candidate ? { candidate: f.candidate } : {}), version: report.version, profiles });
}

const lines: string[] = ["# Harness summary", "", "Generated by scripts/design/phase3-summary.ts. Each profile: status, errors, warnings, waived, number of checks. The tightest checks are the passing ones closest to their limit, in relative terms.", ""];
lines.push("| Family | Version | Profile | Status | Errors | Warnings | Waived | Checks |", "|---|---|---|---|---|---|---|---|");
for (const e of entries) {
  for (const [name, p] of Object.entries(e.profiles)) lines.push(`| ${e.name} | ${e.version} | ${name} | ${p.status} | ${p.errors} | ${p.warnings} | ${p.waived} | ${p.checks} |`);
}
lines.push("", "## Tightest checks", "");
for (const e of entries) {
  lines.push(`### ${e.name}`, "");
  for (const [name, p] of Object.entries(e.profiles)) {
    if (p.tightest.length === 0) continue;
    lines.push(`${name}:`);
    for (const t of p.tightest) lines.push(`- ${t.detail}`);
    lines.push("");
  }
}

const out = join(root, "docs/migration/phase3");
mkdirSync(out, { recursive: true });
writeFileSync(join(out, "summary.md"), lines.join("\n") + "\n");
writeFileSync(join(out, "summary.json"), JSON.stringify(entries, null, 2) + "\n");
console.log(`wrote docs/migration/phase3/summary.md for ${entries.length} families and candidates`);
