// assets/tokens.css: one block of custom properties per family (or candidate) and
// mode, the Pequod values for the page itself, and one class per colour address
// for swatches and samples. Colour values reach CSS only from here, and only from
// the resolved token files.
import { MODES } from "../../lib/model/types.ts";
import type { ResolvedFamily } from "../../lib/model/types.ts";

export interface Scope {
  /** The data-scope value: the family id, or <id>--<candidate>. */
  scope: string;
  family: ResolvedFamily;
}

import { addressClass, addressProperty, designRefName, scopeProperties } from "../../lib/generators/css-properties.ts";
export { addressClass, addressProperty, cssColour, designLeaves, designRefName, scopeProperties } from "../../lib/generators/css-properties.ts";

const block = (selector: string, props: [string, string][], indent = ""): string =>
  `${indent}${selector} {\n${props.map(([k, v]) => `${indent}  ${k}: ${v};`).join("\n")}\n${indent}}\n`;

/** The border widths that achromatic status levels name, as design-... names. */
function statusWeights(scopes: Scope[]): string[] {
  const out = new Set<string>();
  for (const { family } of scopes) {
    for (const mode of MODES) {
      const status = family.source.modes[mode].status;
      if (status?.policy !== "achromatic") continue;
      for (const level of [status.neutral, status.success, status.warning, status.critical]) out.add(designRefName(level.weight));
    }
  }
  return [...out];
}

/** chrome is the family whose values the page itself takes (Pequod); without it the page keeps the browser's defaults. */
export function tokensCss(scopes: Scope[], chrome: ResolvedFamily | undefined): string {
  const parts = ["/* Generated by scripts/pages/build.ts from the family token files. Do not edit. */\n"];
  if (chrome) {
    parts.push(block(":root", [["color-scheme", "light dark"], ...scopeProperties(chrome, "light")]));
    parts.push(`@media (prefers-color-scheme: dark) {\n${block(":root", scopeProperties(chrome, "dark"), "  ")}}\n`);
  } else {
    parts.push(block(":root", [["color-scheme", "light dark"]]));
  }
  for (const { scope, family } of scopes) {
    for (const mode of MODES) parts.push(block(`[data-scope="${scope}"][data-mode="${mode}"]`, scopeProperties(family, mode)));
  }

  const addresses = new Set<string>();
  for (const { family } of scopes) for (const mode of MODES) for (const a of family.modes[mode].colours.keys()) addresses.add(a);
  const each = (make: (cls: string, prop: string) => string) => [...addresses].map((a) => make(addressClass(a), addressProperty(a))).join("");
  parts.push("\n/* Swatches and sample backgrounds. */\n", each((c, p) => `.sw-${c} { background-color: var(${p}); }\n`));
  parts.push("\n/* Sample text colours. */\n", each((c, p) => `.fg-${c} { color: var(${p}); }\n`));
  parts.push("\n/* Sample border colours. */\n", each((c, p) => `.bc-${c} { border-color: var(${p}); }\n`));
  const weights = statusWeights(scopes);
  if (weights.length > 0) parts.push("\n/* Border widths of achromatic status levels. */\n", ...weights.map((w) => `.bw-${w} { border-width: var(--${w}); }\n`));
  return parts.join("");
}
