import { MODES } from "../model/types.ts";
import type { ModeName, ResolvedFamily } from "../model/types.ts";
import type { ExportOptions } from "./types.ts";

export function modesOf(options: ExportOptions = {}): readonly ModeName[] {
  const mode = options.mode ?? "both";
  if (mode === "both") return MODES;
  if (mode === "dark" || mode === "light") return [mode];
  throw new Error(`Unknown mode: ${String(mode)}`);
}

export const json = (value: unknown): string => JSON.stringify(value, null, 2) + "\n";

/** No clock or repository state: the same input always produces the same bytes. */
export function provenance(family: ResolvedFamily): string {
  return `${family.meta.name} ${family.meta.version}. Generated by Ensigns, https://ensigns.tiagojacinto.eu. Tokens CC BY 4.0, Tiago Jacinto.`;
}

export function familyId(family: ResolvedFamily): string {
  const id = family.meta.id;
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id)) throw new Error(`Invalid family id: ${id}`);
  return id;
}

export const textHeader = (family: ResolvedFamily): string => `# ${provenance(family).replace(/[\r\n]/g, " ")}\n`;
