// Installation copy shared by the web workbench and release documentation.
export const INSTALL: Readonly<Record<string,string>> = {
  css:'Include the stylesheet. It follows the system appearance; set data-mode="light" or data-mode="dark" on a containing element to override it. Colours use --roles-*, --accents-* and other address-based custom properties. Fonts are named but not embedded.',
  json:'Read the resolved JSON as data. Each colour includes its palette origin, optional opacity and syntax style. Canonical tokens are included in the family bundle.',
  scss:'Import the partial with Sass @use. Each mode is a Sass map of CSS-ready strings. Read entries with sass:map.get, then interpolate the value into a declaration.',
  tailwind3:'Require the .cjs configuration and merge theme.extend.colors into your Tailwind v3 configuration. Role names include the family and mode, for example bg-pequod-light-bg.',
  tailwind4:'Import the theme file after @import "tailwindcss". Utilities include the family and mode, for example bg-pequod-dark-bg. The file defines colour utilities for both modes; select the appropriate utility in your markup.',
  dtcg:'Import the JSON into a tool supporting the DTCG 2025.10 colour-space object. Palette and mode sets preserve every resolved colour. Design and non-colour status cues are included in the Ensigns extension metadata.',
  'tokens-studio':'Import the JSON into Tokens Studio. Enable palette and your chosen mode set. CSS colour values preserve opacity; the Ensigns extension metadata carries typography, design and status cues.',
  'quarto-brand':'Rename the file to _brand.yml in your Quarto project. It contains one colour set; both-mode exports select light. Use the SCSS format for mode-specific HTML themes.',
  'quarto-scss':'Add the selected file to format.html.theme in your Quarto YAML, after a base theme. Use a light/dark theme mapping if you want a mode switch. Syntax rules are included only where the family authored them.',
  typst:'Import the .typ file. Access the family dictionary and its light or dark dictionary with .at("roles-text"), for example #set text(fill: pequod.light.at("roles-text")). Opaque resolved colours are included.',
  latex:'Load xcolor, then input the colours .tex file. Names combine family, mode and address in CamelCase, for example PequodLightRolesText. Opaque resolved colours are included.',
  'pandoc-css':'Pass the selected stylesheet to pandoc --standalone --css FILE.css. Syntax colours apply to Pandoc sourceCode classes where authored. Each stylesheet contains one mode.',
  ggplot2:'source() the R file. Call theme_FAMILY(mode="light") and a named scale function. Function names use underscores. Every authored sequential and diverging ramp has its own function. Keep series labels and the marker/pattern cues from the accompanying JSON.',
  matplotlib:'Put the style sheets and Python module in the same folder. Import matplotlib.pyplot before importing the colours module, then call use("light") or use("dark"). Call register_cmaps() to register every authored ramp. Keep labels and marker/pattern cues carried in DATA.',
  observable:'Import the light or dark object from the JavaScript module. Use Object.values(mode.categorical) as an ordinal colour range, or select a named sequential or diverging ramp. Preserve labels and authored pattern/marker cues.',
  vscode:'Download the family bundle. Copy exports/vscode into ~/.vscode/extensions/tiagojct.ensigns-FAMILY-VERSION (Windows: %USERPROFILE%\\.vscode\\extensions). Restart VS Code, then choose the family in Preferences: Color Theme. The package.json manifest must stay beside its theme JSON files.',
  zed:'Copy the JSON into ~/.config/zed/themes/. Open Zed’s theme selector and choose the family and mode.',
  neovim:'Copy a Lua theme into ~/.config/nvim/colors/. Use :colorscheme FAMILY-dark or :colorscheme FAMILY-light. True colour is enabled by the theme.',
  obsidian:'Copy the CSS into your vault’s .obsidian/snippets/ folder. Enable it in Settings → Appearance → CSS snippets. It follows Obsidian’s light/dark classes. Fonts are named but not bundled in the snippet.',
  ghostty:'Copy a theme to ~/.config/ghostty/themes/ and set theme = FAMILY-dark or FAMILY-light in Ghostty’s configuration.',
  kitty:'Save the .conf file beside kitty.conf and add include FAMILY-dark.conf (or the light filename). Reload the configuration.',
  alacritty:'Save the TOML file in your Alacritty configuration folder and add its absolute path to general.import in alacritty.toml.',
  'windows-terminal':'Paste the JSON object into the schemes array in Windows Terminal settings.json. Set a profile’s colorScheme to the exported scheme name. Windows Terminal cannot set separate selection text or cursor text colours.',
  wezterm:'Save the Lua file locally. In wezterm.lua set config.colors = dofile("/absolute/path/to/FAMILY-dark.lua"). The file returns a colours table.',
  tmux:'Add source-file /absolute/path/to/FAMILY-dark.conf to ~/.tmux.conf, then reload it with tmux source-file ~/.tmux.conf.',
  iterm2:'Import the .itermcolors file in Settings → Profiles → Colors → Color Presets → Import, then choose that preset.',
  gpl:'Import the .gpl file into GIMP or Inkscape’s palette folder, then restart or refresh the application. Only opaque palette entries are included.',
  ase:'Import the .ase file through your application’s swatch panel. Adobe Swatch Exchange contains opaque RGB swatches; translucent overlays are available in the CSS and token exports.',
  hex:'Read the text list of opaque hex values and palette labels. Translucent overlays remain in the CSS and token exports.',
};
